# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be78e3488549afcb1f9b6e0b42674ec503c399514fcbcee4701a916fe156dc125498e0fdc6f952b7b5e83827e15aced80fb8d198a2f05b48158fe18496f7e735

test:
  secret_key_base: 79fb36b41e9fc306f22a4a2d13610e292e376dcf1caa3c30011c09d3e571c3d151bde5bc8ffd08584e7dbc7ffe81a1a984ded0d59e2f16281fc86a529e34376c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
